VERSION 0.8
IMPORT .. AS common

ARG --global BASE_VERSION
ARG --global TAG
ARG --global GITHUB_REPOSITORY_OWNER

qemu-user-static-base:
    FROM docker.io/multiarch/qemu-user-static:${BASE_VERSION}
    DO common+ADD_LABELS

validate:
    FROM +qemu-user-static-base
    RUN --no-cache test -n "$BASE_VERSION" || (echo "BASE_VERSION is required" && exit 1)

build:
    BUILD +validate
    FROM +qemu-user-static-base
    DO common+SAVE_IMAGE --IMAGE_NAME=qemu-user-static --TAG=${TAG} --GITHUB_REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER}

build-multiplatform:
    DO --pass-args common+BUILD_MULTIPLATFORM --TARGET=./qemu-user-static+build
