VERSION 0.8
IMPORT .. AS common

ARG --global BASE_VERSION
ARG --global TAG
ARG --global GITHUB_REPOSITORY_OWNER
ARG BUILDX_VERSION=v0.20.1

docker-base:
    FROM docker.io/docker:${BASE_VERSION}-dind
    RUN apk add --no-cache \
        parallel \
        kubectl \
        bash \
        wget \
        ca-certificates
    RUN mkdir -p ~/.docker/cli-plugins && \
        wget -O ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.linux-amd64 && \
        chmod +x ~/.docker/cli-plugins/docker-buildx
    RUN docker buildx version
    DO common+ADD_LABELS

validate:
    FROM +docker-base
    RUN --no-cache test -n "$BASE_VERSION" || (echo "BASE_VERSION is required" && exit 1)

build:
    BUILD +validate
    FROM +docker-base
    DO common+SAVE_IMAGE --IMAGE_NAME=docker --TAG=${TAG} --GITHUB_REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER}

build-multiplatform:
    DO common+BUILD_MULTIPLATFORM --TARGET=./docker+build
