VERSION 0.8
IMPORT .. AS common

ARG --global BASE_VERSION
ARG --global TAG
ARG --global GITHUB_REPOSITORY_OWNER

minio-base:
    FROM docker.io/bitnamilegacy/minio:${BASE_VERSION}
    DO common+ADD_LABELS

validate:
    FROM +minio-base
    RUN --no-cache test -n "$BASE_VERSION" || (echo "BASE_VERSION is required" && exit 1)

build:
    BUILD +validate
    FROM +minio-base
    DO common+SAVE_IMAGE --IMAGE_NAME=minio --TAG=${TAG} --GITHUB_REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER}

build-multiplatform:
    DO common+BUILD_MULTIPLATFORM --TARGET=+build
