name: Test

on:
  pull_request:

permissions:
  contents: read

jobs:
  matrix:
    name: Generate Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed
        uses: tj-actions/changed-files@v45
        with:
          separator: ","
          files: |
            containers/**
            dev/**

      - name: Install dependencies
        run: pip install poetry && poetry install

      - name: Generate matrix
        id: set-matrix
        run: echo "matrix=$(poetry run containers matrix --changed-files '${{ steps.changed.outputs.all_changed_files }}')" >> $GITHUB_OUTPUT

  build:
    name: Build ${{ matrix.container }}:${{ matrix.tag }}
    needs: matrix
    if: needs.matrix.outputs.matrix != '{"include":[]}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install poetry && poetry install

      - name: Install Earthly
        uses: earthly/actions-setup@v1
        with:
          version: latest

      - name: Build ${{ matrix.container }}:${{ matrix.tag }}
        run: poetry run containers build ${{ matrix.container }} --version ${{ matrix.version }}
